### ISSUE TITLE
Dodac Price and Stocks do Listy Produktow

### ISSUE THREAD

**Issue by meteogish** [ProjectTME/projTME#17]
Dodac wlasciwosci Price(float) i Stock(int) do Store.Domain.Product + ctor
W ProductsView.xaml zamienic mocki na te wlasciwosci
W ProductsProvider dodac logike wyszukiwania najnizszej ceny (LINQ.Min)

Logika na Stocks
Zamienic IPricesProvider na IApiPricesAndStocksProvider
lub
Uzyc po prostu IStocksProvider

**Comment by maroch** [comment]
it seems to be done
